---
- name: Create {{ container_group }}
  group:
    name: "{{ container_group }}"
    gid: 9999

- name: Create {{ container_user }}
  user:
    name: "{{ container_user }}"
    comment: "{{ container_user | capitalize() }} User"
    uid: 9999
    group: "{{ container_group }}"

- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: no
    state: latest
  with_items:
    - apt-transport-https
    - build-essential
    - ca-certificates
    - curl
    - git
    - language-pack-en
    - locales
    - psmisc
    - software-properties-common

- name: Create sensu monitor directory
  file:
    path: /monitoring/sensu
    state: directory

- name: Copy sensu.sh
  copy:
    src: sensu.sh
    dest: /monitoring/sensu/sensu.sh
    mode: "0755"

- name: Ensure UTF-8 locale
  shell: "locale-gen en_US.UTF-8 && dpkg-reconfigure locales"

- name: Cleanup task
  shell: "apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/"
